galaxy_info:
  author: Tyler Smith <tyler@entropygra.ph>
  description: Management for subnet_evm instances
  company: EntropyGraph
  license: MIT
  min_ansible_version: '2.1'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
