galaxy_info:
  author: Tyler Smith <tyler@entropygra.ph>
  description: Ansible host facilities
  company: EntropyGraph
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
