---

- name: Disk
  ansible.builtin.include_tasks: disk.yml
  args:
    apply:
      tags: disk
  tags:
    - disk

- name: Setup
  ansible.builtin.include_tasks: setup.yml
  args:
    apply:
      tags: setup
  tags:
    - setup

- name: Deploy
  ansible.builtin.include_tasks: deploy.yml
  args:
    apply:
      tags: deploy
  tags:
    - deploy
